default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: ankiprotest_development

test:
    <<: *default
    database: ankiprotest_test
    host: localhost

production:
    <<: *default
    database: ankiprotest_production
